<?php
require_once ("Manager.php");
require_once ("Classes.php");

class RightManager extends Manager
{
    protected $pdo;

    public function __construct($con)
    {
        parent::__construct($con);
    }

    public function __destruct()//Destruktor der pdo (auflösen/lösen der Connection zwischen der DB)
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }
}